version: '3.8'

services:
  flb:
    build: ./plugin/
    command: /fluent-bit/bin/fluent-bit -c /etc/fluent-bit/flb.conf
    volumes:
      - type: volume
        source: flb-data
        target: /var/log/flb-storage
        read_only: false
      - type: bind
        source: ./
        target: /etc/fluent-bit

volumes:
  flb-data:
